### PR TITLE
Dark Mode, Localizations

### PR DESCRIPTION
**Pull request by Dirk-**
- Compiles with ARC, Xcode 10.3, target 10.8. Runs on macOS 10.14.
- Localizations for French, Dutch, German

### CODE REVIEW

**Comment by specialunderwear** [comment]
Awesome!!

**Comment by specialunderwear** [comment]
i'm going to run it for a while and test.

**Comment by Dirk-** [comment]
Great, thank you.

**Comment by filliph** [comment]
Would it be possible for you to provide a compiled version for those of us who don't have much experience using Xcode? Thanks in advance!

**Comment by Dirk-** [comment]
> Would it be possible for you to provide a compiled version for those of us who don't have much experience using Xcode? Thanks in advance!

@filliph I just added a "Products" folder with ZIP archives of the app and the pref pane in [my branch](https://github.com/Dirk-/Hosts.prefpane). You can download the files from there.

**Comment by filliph** [comment]
Got it, thanks 😄

Would it also be possible to support dark mode? I don't know if that's a lot of work, so it's not a huge problem if it isn't, but it would be nice to have 😄

Regardless, thank you so much for your work on keeping this alive. I don't need it often, but when I do, it's very useful!

**Comment by Dirk-** [comment]
@filliph It does support Dark Mode, works on my system. Doesn't it work for you?

**Comment by filliph** [comment]
@Dirk- The .app file does, the .prefpane does not.

image

**Comment by Dirk-** [comment]
@filliph Which system is that? It works for me on 10.14.6, I installed it under /Users/<user>/Library/PreferencePanes/Hosts.prefPane

Bildschirmfoto 2019-10-13 um 16 11 40

**Comment by filliph** [comment]
10.15, Mid-2015 rMBP 15".

That's the same location it's installed in for me as well.

**Comment by filliph** [comment]
Works perfectly now, thank you!

**Comment by Dirk-** [comment]
@filliph Can you try it again with the new binaries I just uploaded? I don't have 10.15 installed yet, so I don't know it it works this time.

**Comment by Dirk-** [comment]
@filliph That was fast. Great!

**Comment by hasnat** [comment]
thanks @Dirk- , I tried .app on 10.15 (works).

**Comment by specialunderwear** [comment]
Thanks for this!

**Pull request merged**
